### ISSUE TITLE
关于位置监听函数

### ISSUE THREAD

**Issue by yuefeng007** [best-flutter/flutter_amap_location#29]
当上一个监听任务执行停止后，
如继续开启新的监听任务。
那么、、
两个监听任务又同时开启了，

 如何销毁上一个监听任务呢？？？
1.只能停止当前监听行为
` AMapLocationClient.stopLocation();`
2.也不能销毁任务
` void dispose() {
      AMapLocationClient.shutdown();//销毁任务
    super.dispose();
  }`

**Comment by kuww** [comment]
你这个bug怎么解决的
