### ISSUE TITLE
大佬你好，监听位置变化时会出现一下报错。不知道是不是我打开方式不对

### ISSUE THREAD

**Issue by china17qin** [best-flutter/flutter_amap_location#3]
For a more detailed help message, press "h". To quit, press "q".
D/AmapLocationPugin( 7359): 定位获取结果:37.422075 code：0 省:California
W/System.err( 7359): com.loc.k: IO 操作异常 - IOException
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bk.a(BaseNetManager.java)
W/System.err( 7359):    at com.loc.db.a(LocNetManager.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.d.b(AmapLocationManager.java)
W/System.err( 7359):    at com.loc.d.f(AmapLocationManager.java)
W/System.err( 7359):    at com.loc.d$a.handleMessage(AmapLocationManager.java)
W/System.err( 7359):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7359):    at android.os.Looper.loop(Looper.java:148)
W/System.err( 7359):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 7359):    at com.loc.d$b.run(AmapLocationManager.java)
W/System.err( 7359): com.loc.k: IO 操作异常 - IOException
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bk.a(BaseNetManager.java)
W/System.err( 7359):    at com.loc.db.a(LocNetManager.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.d.b(AmapLocationManager.java)
W/System.err( 7359):    at com.loc.d.f(AmapLocationManager.java)
W/System.err( 7359):    at com.loc.d$a.handleMessage(AmapLocationManager.java)
W/System.err( 7359):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7359):    at android.os.Looper.loop(Looper.java:148)
W/System.err( 7359):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 7359):    at com.loc.d$b.run(AmapLocationManager.java)
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
I/authErrLog( 7359): 
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
W/System.err( 7359): com.loc.k: IO 操作异常 - IOException
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bk.a(BaseNetManager.java)
W/System.err( 7359):    at com.loc.bk.b(BaseNetManager.java)
W/System.err( 7359):    at com.loc.db.a(LocNetManager.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.e.a(ApsManager.java)
W/System.err( 7359):    at com.loc.e$a.handleMessage(ApsManager.java)
W/System.err( 7359):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7359):    at android.os.Looper.loop(Looper.java:148)
W/System.err( 7359):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 7359):    at com.loc.e$b.run(ApsManager.java)
W/System.err( 7359): com.loc.k: IO 操作异常 - IOException
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bk.a(BaseNetManager.java)
W/System.err( 7359):    at com.loc.bk.b(BaseNetManager.java)
W/System.err( 7359):    at com.loc.db.a(LocNetManager.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.e.a(ApsManager.java)
W/System.err( 7359):    at com.loc.e$a.handleMessage(ApsManager.java)
W/System.err( 7359):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7359):    at android.os.Looper.loop(Looper.java:148)
W/System.err( 7359):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 7359):    at com.loc.e$b.run(ApsManager.java)
W/System.err( 7359): com.loc.k: IO 操作异常 - IOException
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bk.a(BaseNetManager.java)
W/System.err( 7359):    at com.loc.db.a(LocNetManager.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.cm.d(Aps.java)
W/System.err( 7359):    at com.loc.e.b(ApsManager.java)
W/System.err( 7359):    at com.loc.e$a.handleMessage(ApsManager.java)
W/System.err( 7359):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7359):    at android.os.Looper.loop(Looper.java:148)
W/System.err( 7359):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 7359):    at com.loc.e$b.run(ApsManager.java)
W/System.err( 7359): com.loc.k: IO 操作异常 - IOException
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bn.a(HttpUrlUtil.java)
W/System.err( 7359):    at com.loc.bk.a(BaseNetManager.java)
W/System.err( 7359):    at com.loc.db.a(LocNetManager.java)
W/System.err( 7359):    at com.loc.cm.a(Aps.java)
W/System.err( 7359):    at com.loc.cm.d(Aps.java)
W/System.err( 7359):    at com.loc.e.b(ApsManager.java)
W/System.err( 7359):    at com.loc.e$a.handleMessage(ApsManager.java)
W/System.err( 7359):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7359):    at android.os.Looper.loop(Looper.java:148)
W/System.err( 7359):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 7359):    at com.loc.e$b.run(ApsManager.java)
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:
D/AmapLocationPugin( 7359): 定位获取结果:22.011949782470765 code：0 省:

**Comment by jzoom** [comment]
是真机调试吗,如果是模拟器有时候不能获取地理位置，有问题可以加群854192563交流
