### ISSUE TITLE
小米9手机闪退

### ISSUE THREAD

**Issue by zzy216** [best-flutter/flutter_amap_location#36]
小米手机 MI9    
MUI11 9.9.25版本
Android 10打开地图定位直接闪退
 AMapLocation loc = await AMapLocationClient.getLocation(false); 这句代码

**Comment by zzy216** [comment]
> 小米手机 MI9
> MUI11 9.9.25版本
> Android 10打开地图定位直接闪退
> AMapLocation loc = await AMapLocationClient.getLocation(false); 这句代码

是在release的情况下。

**Comment by louyanqi** [comment]
同android10闪退,荣耀v20

**Comment by zzy216** [comment]
找到问题了，是打包后混淆问题，在混淆文件
-keep class com.loc.**{*;}  加上这个
