### ISSUE TITLE
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

### ISSUE THREAD

**Issue by virskor** [best-flutter/flutter_amap_location#37]
Building plugin amap_location...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    1.8s
WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
The current default is 'false'
Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'amap_location'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin amap_location could not be built due to the issue above.

**Comment by jiangyh1024** [comment]
@virskor 
I'm encountering this problem too. Have u solved it ?

**Comment by virskor** [comment]
@ jiangyh1024 modify your build.gradle file to support AndroidX and API level 28. it worked fine after modify.
