### ISSUE TITLE
simple_permissions not working, can't complie

### ISSUE THREAD

**Issue by a396901990** [best-flutter/flutter_amap_location#6]
after compile on iOS will raising a error `simple_permissions/simple_permissions-Swift.h' file not found`
pls check it.

btw, it's working on android perfectly~

**Comment by a396901990** [comment]
i think u should remove simple_permission from the plugin, because it did't use at all

**Comment by pptavozl** [comment]
where can i find amap_location.podspec ?

**Comment by JunevaYang** [comment]
The same as my question， how to find amap_location.podspec ? thx

**Comment by karedem** [comment]
i fixed it by this way:
Targets - Build Settings - packaging 
   Defines Module 设置为Yes
